### PR TITLE
feat: french translation

### PR DESCRIPTION
**Pull request by whiterqbbit**
Hey, I translated this in french. 
I didn't make a .mo file thought.

### CODE REVIEW

**Comment by esenliyim** [comment]
Merci beaucoup. Don't worry about the .mo, I can take care of it.

I'll include your translation with the next version, which I'll try to upload this weekend, if I can find the time. Kinda busy with more important things these days, unfortunately.

**Comment by esenliyim** [comment]
Oh damn you're right, the structure is indeed wrong. I should have reviewed it more carefully. Good catch.

@whiterqbbit I was gonna do the compiling anyway, in the meantime I took care of placing the file where it should have been in the first place. I should have been more careful, but I'd appreciate it if you were also more careful next time.

**Comment by whiterqbbit** [comment]
My bad!
I'm really sorry and thanks Michael for pointing it out :)

**Comment by esenliyim** [comment]
Since then some new strings have been added. I learned French some years ago, haven't really spoken it for like 10 years or so, and right now I'm only good for detecting when Google Translate's results are way off, but I can't really correct them myself. 

I'd much appreciate it if one of you fine people could give the French localization a look.

**Comment by esenliyim** [comment]
With one of the last commits I've also introduced 5-6 new strings, which I haven't translated. I mean I tried, but Google Translate's results felt wrong so I left them untouched. That's actually what prompted this request in the first place.

**Comment by whiterqbbit** [comment]
I see! Added them.

**Pull request merged**
